incountry/sdk-python

- incountry/incountry_crypto.py
- setup.py
- tests/test_client.py
Bugfixes for crypto error and workaround for tests.
> FB_EN-1019

- .travis.yml
- [SEC-50 ] Embed Snyk into CI pipeline.
------------
CI change only.
> SEC-50 Embed Snyk into CI.

- README.md
- [ EN-1302 ]
------------
Target Release
--------------
> Replaced Japan with Russia in README

- README.md
- incountry/storage.py
- tests/integration/popapi_integrations_test.py
------------
Target Release
--------------
> [EN-1152] Fix documentation first. Add more solid integration testing.

- README.md
- incountry/storage.py
- setup.py
[ENH] now retrieving countries list and checking for mid/mini pop when constructing endpoint
[FIX] readme typo
https://incountry.atlassian.net/browse/EN-1317
------------
Target Release
--------------
> FB EN 1317

- README.md
- incountry/storage.py
- setup.py
- tests/integration/popapi_integrations_test.py
[ENH] Update get_endpoint to force usage of custom endpoint if provided
[CLN] update formatting
[CLN] remove unused imports
Updated Version to 0.3.1 (for pypi)
- https://incountry.atlassian.net/browse/EN-997
------------
Target Release
--------------
> Fb en 1328

- incountry/storage.py
- setup.py
- tests/unit/test_storage.py
[ENH] add update_one method and unit tests for it
[ENH] minor linting updates
- https://incountry.atlassian.net/browse/EN-1351
------------
Target Release
--------------
> EN-1351Python SDK add support to update record by custom key

- incountry/__init__.py
- incountry/exceptions.py
- incountry/incountry_crypto.py
- incountry/secret_key_accessor.py
- incountry/storage.py
- setup.py
- tests/unit/test_crypto.py
- tests/unit/test_secrey_key_accessor.py
- tests/unit/test_storage.py
- https://incountry.atlassian.net/browse/EN-1460
------------
Target Release
--------------
> EN 1460 All SDKs must allow for a custom strategy for allowing access to secret to use for encryption

- incountry/incountry_crypto.py
- tests/unit/test_crypto.py
------------
Target Release
--------------
> FB_EN-1417 Change from using Hex for encrypted Payloads to Base64

- .travis.yml
- Pipfile
------------
Target Release
--------------
> FB_EN-1491 add run tests

- Pipfile
- README.md
- tests/integration/popapi_integrations_test.py
- tests/integration/test_storage.py
- [https://incountry.atlassian.net/browse/EN-1505 ]
------------
Target Release
--------------
> Fb en 1505

- README.md
- incountry/storage.py
[ENH] Update README with better code samples 
[CLN] remove unused pydoc line
- https://incountry.atlassian.net/browse/EN-1528
------------
Target Release
--------------
> EN-1528 Update Python SDK README to add better code examples

- setup.py
[FIX] update setup.py to contain proper required deps list
- https://incountry.atlassian.net/browse/EN-1553
------------
Target Release
--------------
> EN-1553 SDK Python - make sure `cryptography` module is installed (is in lock file)

- Pipfile
- Pipfile.lock
- incountry/incountry_crypto.py
- incountry/secret_key_accessor.py
- incountry/storage.py
- incountry/validation.py
- tests/unit/test_crypto.py
- tests/unit/test_secrey_key_accessor.py
- tests/unit/test_storage.py
[ENH] Add support for multiple keys in SecretKeyAccessor
[ENH] Add key version management for storage/crypto
[ENH] add jsonschema validation for SecretKeyAccessor callback result
[ENH] add jsonschema to deps
[ENH] update tests to accomodate latest changes
- https://incountry.atlassian.net/browse/EN-1586
------------
Target Release
--------------
> EN-1586 Python SDK should accept multiple secrets via SecretKeyAccessor

- incountry/storage.py
- incountry/validation.py
- tests/unit/test_storage.py
[ENH] add batch_write method (and tests for it)
- https://incountry.atlassian.net/browse/EN-1589
------------
Target Release
--------------
> EN-1589 Python SDK should have batchWrite method

- examples/full_migration.py
[ENH] add migration script example
- https://incountry.atlassian.net/browse/EN-1595
------------
Target Release
--------------
> EN-1595 Python SDK should provide migration script example

- README.md
[ENH] update README.md with information about SecretKeyAccessor enhancement, batchWrite, migrate and migration script example
- https://incountry.atlassian.net/browse/EN-1672
------------
Target Release
--------------
> EN-1672 Add migration/key rotation README notes for Python SDK

- .travis.yml
- Pipfile
- sonar-project.properties
- tests/integration/popapi_integrations_test.py
- tests/integration/test_storage.py
------------
Target Release
--------------
> EN-1491 Run test on each commit in sdk-python

- incountry/incountry_crypto.py
- incountry/storage.py
- tests/unit/test_crypto.py
- tests/unit/test_storage.py
- https://incountry.atlassian.net/browse/EN-1777
------------
Target Release
--------------
> EN-1777 Add plaintext (in no-encryption mode) crypto-version support to Python SDK

- .gitignore
- incountry/incountry_crypto.py
- incountry/storage.py
- tests/integration/popapi_integrations_test.py
- tests/integration/test_storage.py
- tests/unit/test_crypto.py
- tests/unit/test_storage.py
- https://incountry.atlassian.net/browse/EN-1786
------------
Target Release
--------------
> EN-1786 Merge RC_1.0.0 into develop for Python SDK

- incountry/storage.py
- tests/integration/popapi_integrations_test.py
- tests/integration/test_storage.py
- tests/unit/test_storage.py
[ENH] update SDK methods to return dicts with record/meta/result data instead of random data types
[ENH] update unit/int tests
- https://incountry.atlassian.net/browse/EN-1563
------------
Target Release
--------------
> EN-1563 Refactor Python SDK to not use Request/Response objects

- .gitignore
- .travis.yml
- Pipfile
- sonar-project.properties
------------
Target Release
--------------
> EN-1843 Split unit and integration tests

- .gitignore
- .travis.yml
- Pipfile
- Pipfile.lock
- README.md
- incountry/incountry_crypto.py
- pyproject.toml
- setup.cfg
- setup.py
- tests/integration/popapi_integrations_test.py
- tests/integration/test_storage.py
[ENH] add black+flake8 checks to travis
[ENH] reorganised pipfile
[CLN] minor linting
- https://incountry.atlassian.net/browse/EN-1866
------------
Target Release
--------------
> EN-1866 Python SDK - Enforce Coding standards

- incountry/storage.py
- tests/unit/test_storage.py
------------
Target Release
--------------
> EN-1929 Change batchWrite payload format.

- incountry/incountry_crypto.py
- tests/unit/test_crypto.py
------------
Target Release
--------------
> EN-1876 Remove decrypt_v0.

- Pipfile
- incountry/storage.py
- pull_request_template.md
- tests/integration/popapi_integrations_test.py
- tests/integration/test_storage.py
- tests/unit/test_storage.py
- https://incountry.atlassian.net/browse/EN-1563
------------
Target Release
--------------
> EN-1563 Refactor Python SDK to not use Request/Response objects - 3

- incountry/storage.py
[FIX] update find method offset validation error text
- https://incountry.atlassian.net/browse/EN-1984
------------
Target Release
--------------
> EN-1984 [Python SDK] Find method - offset validation error message needs fix

- Pipfile
- incountry/storage.py
- tests/unit/test_storage.py
[FIX] now requiring limit param in find method to be > 0
[ENH] add new test case
[FIX] brought back term-missing for coverage report
- https://incountry.atlassian.net/browse/EN-1983
------------
Target Release
--------------
> EN-1983 [Python SDK] Find method - limit cannot be 0, fix in validation needed

- incountry/storage.py
Reverts incountry/sdk-python#47
> Revert "EN-1984 [Python SDK] Find method - offset validation error message needs fix"

- incountry/incountry_crypto.py
- incountry/storage.py
- tests/unit/test_crypto.py
- tests/unit/test_storage.py
------------
Target Release
--------------
> EN-2034 Do not throw error if can't parse/decrypt record in Find results

- README.md
------------
Target Release
--------------
> EN-2065 [Python SDK] Update README's Find section with some meaningful text regarding enhancements to response format (errors list as a new param) 

- setup.py
[FIX] add jsonschema to setup.py
- [EN-1878](https://incountry.atlassian.net/browse/EN-1878)
------------
Target Release
--------------
> EN-1878 [Python SDK] develop branch: No module named 'jsonschema' error

- setup.py
[ENH] bumped version in setup.py
- https://incountry.atlassian.net/browse/EN-2117
------------
Target Release
--------------
> EN-2117 [Python SDK] bump RC_1.1.0 version

- incountry/storage.py
- incountry/validation.py
- tests/unit/test_storage.py
------------
Target Release
--------------
> EN-1971 [Python SDK] Validate PoPAPI response

- incountry/incountry_crypto.py
- incountry/secret_key_accessor.py
- incountry/storage.py
- incountry/validation/schemas.py
- incountry/validation/validator.py
- tests/unit/test_crypto.py
- tests/unit/test_secret_key_accessor.py
- tests/unit/test_storage.py
- [EN-1764](https://incountry.atlassian.net/browse/EN-1764)
------------
Target Release
--------------
> EN-1764 [Python SDK] Add custom encryption support

- README.md
[ENH] add custom encryption section to README.md
- [EN-1764](https://incountry.atlassian.net/browse/EN-1764)
------------
Target Release
--------------
> EN-1764 [Python SDK] Add custom encryption support - 2

- incountry/storage.py
------------
Target Release
--------------
> EN-2143 remove country from record data for writing

- Pipfile
- Pipfile.lock
- incountry/__init__.py
- incountry/models/__init__.py
- incountry/models/country.py
- incountry/models/find_filter.py
- incountry/models/record.py
- incountry/models/record_list_for_batch.py
- incountry/storage.py
- incountry/validation/schemas.py
- incountry/validation/validate_model.py
- setup.cfg
- setup.py
- tests/integration/test_methods.py
- tests/integration/test_migrate.py
- tests/unit/test_storage.py
- [EN-1974](https://incountry.atlassian.net/browse/EN-1974)
------------
Target Release
--------------
> EN-1974 [Python SDK] Validate public method arguments

- incountry/models/record.py
- tests/unit/test_models.py
- [EN-2432](https://incountry.atlassian.net/browse/EN-2432)
------------
Target Release
--------------
> EN-2432 [Python SDK] Read validation allows user to pass a record key as an empty string

- README.md
- incountry/storage.py
- tests/integration/test_methods.py
- tests/unit/test_storage.py
- [EN-2392](https://incountry.atlassian.net/browse/EN-2392)
------------
Target Release
--------------
> EN-2392 [Python SDK] Get rid of Update method

- README.md
- incountry/incountry_crypto.py
- incountry/models/__init__.py
- incountry/models/custom_encryption_options.py
- incountry/models/custom_encryption_options_with_key.py
- incountry/models/secret_key_accessor.py
- incountry/models/secrets_data.py
- incountry/models/storage_with_env.py
- incountry/secret_key_accessor.py
- incountry/storage.py
- incountry/validation/__init__.py
- incountry/validation/utils.py
- incountry/validation/validate_custom_encryption_methods.py
- incountry/validation/validate_http_response.py
- incountry/validation/validate_model.py
- tests/unit/test_crypto.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- tests/unit/test_secret_key_accessor.py
- tests/unit/test_storage.py
- [EN-2208](https://incountry.atlassian.net/browse/EN-2208)
------------
Target Release
--------------
> EN-2208 [Python SDK] Validate secrets data/custom encryption methods right after initialization

- README.md
- countries.md
- [SDK-63](https://incountry.atlassian.net/browse/SDK-63)
------------
Target Release
--------------
> SDK-63 [Python SDK] Add Countries section and a separate countries.md file

- countries.md
- pull_request_template.md
- [SDK-63](https://incountry.atlassian.net/browse/SDK-63)
------------
Target Release
--------------
> SDK-63 [Python SDK] Add Countries section and a separate countries.md file - 2

- incountry/crypto_utils.py
- incountry/validation/validate_model.py
- tests/unit/test_storage.py
- tests/unit/test_validation.py
- [SDK-66](https://incountry.atlassian.net/browse/SDK-66)
------------
Target Release
--------------
> SDK-66 [Python SDK] Do not send None/Null record fields to PopAPI (for now)

- README.md
- [SDK-72](https://incountry.atlassian.net/browse/SDK-72)
------------
Target Release
--------------
> SDK-72 [Python SDK] fix README.md padding

- README.md
- countries.md
- pull_request_template.md
- [SDK-76](https://incountry.atlassian.net/browse/SDK-76)
------------
Target Release
--------------
> SDK-76 [Python SDK] Move countries README.md updates to v1.1.1

- setup.py
- [SDK-93](https://incountry.atlassian.net/browse/SDK-93)
------------
Target Release
--------------
> SDK-93 [Python SDK] Bump version for RC_1.1.1

- README.md
- countries.md
- pull_request_template.md
- setup.py
- [SDK-90](https://incountry.atlassian.net/browse/SDK-90)
------------
Target Release
--------------
> SDK-90 [Python SDK] Release RC_1.1.1

- README.md
- [SDK-98](https://incountry.atlassian.net/browse/SDK-98)
------------
Target Release
--------------
> SDK-98 [Python SDK] postpone $not filter for find untill v2.1.0

- incountry/models/record_from_server.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- [SDK-111](https://incountry.atlassian.net/browse/SDK-111)
------------
Target Release
--------------
> SDK-111 [Python SDK] Make http response version validation less strict

- tests/unit/test_compatibility.py
- tests/unit/test_storage.py
…est for record hashes from different storages
- [SDK-119](https://incountry.atlassian.net/browse/SDK-119)
------------
Target Release
--------------
> SDK-119 [Python SDK] Add universal unit tests for encrypt/decrypt payload methods

- incountry/crypto_utils.py
- incountry/models/storage_with_env.py
- incountry/storage.py
- tests/integration/conftest.py
- tests/integration/test_methods.py
- tests/unit/test_models.py
- tests/unit/test_storage.py
- [SDK-17](https://incountry.atlassian.net/browse/SDK-17)
------------
Target Release
--------------
> SDK-17 [Python SDK] To lowercase on all keys

- incountry/http_client.py
- tests/unit/test_http_client.py
- [SDK-124](https://incountry.atlassian.net/browse/SDK-124)
------------
Target Release
--------------
> SDK-124 [Python SDK] Postpone PoPAPI response validation for 2.0.0 release

- README.md
- incountry/token_clients/oauth_token_client.py
- [SDK-131](https://incountry.atlassian.net/browse/SDK-131)
------------
Target Release
--------------
> SDK-131 [Python SDK] Add oAuth section to README.md

- .travis.yml
- README.md
- incountry/http_client.py
- incountry/models/storage_with_env.py
- incountry/storage.py
- incountry/token_clients/api_key_token_client.py
- incountry/token_clients/oauth_token_client.py
- incountry/token_clients/token_client.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- tests/unit/test_storage.py
- [SDK-138](https://incountry.atlassian.net/browse/SDK-138)
------------
Target Release
--------------
> SDK-138 [Python SDK] add ability to provide endpoint mask (and update minipop token acquisition)

- incountry/http_client.py
- incountry/storage.py
- incountry/token_clients/api_key_token_client.py
- incountry/token_clients/oauth_token_client.py
- tests/unit/test_http_client.py
- [SDK-151](https://incountry.atlassian.net/browse/SDK-151)
------------
Target Release
--------------
> SDK-151 [Python SDK] add default regional auth servers 

- setup.py
- [SDK-156](https://incountry.atlassian.net/browse/SDK-156)
------------
Target Release
--------------
> SDK-156 [Python SDK] Release RC_2.0.0 - resolve master conflicts

- incountry/http_client.py
- tests/unit/test_storage.py
- [SDK-151](https://incountry.atlassian.net/browse/SDK-151)
------------
Target Release
--------------
> SDK 151 [Python SDK] add default regional auth servers - extra fixes

- README.md
- incountry/http_client.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- [SDK-151](https://incountry.atlassian.net/browse/SDK-151)
------------
Target Release
--------------
> SDK-151 [Python SDK] add default regional auth servers - update default endpoint mask

- README.md
- incountry/http_client.py
- incountry/models/storage_with_env.py
- incountry/storage.py
- incountry/token_clients/oauth_token_client.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- [SDK-173](https://incountry.atlassian.net/browse/SDK-173)
------------
Target Release
--------------
> SDK-173 [Python SDK] add auth_endpoints Storage option

- README.md
- incountry/http_client.py
- incountry/models/storage_with_env.py
- incountry/storage.py
- incountry/token_clients/oauth_token_client.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- [SDK-173](https://incountry.atlassian.net/browse/SDK-173)
------------
Target Release
--------------
> SDK-173 [Python SDK] add auth_endpoints Storage option - RC branch

- .travis.yml
- README.md
- incountry/storage.py
- sonar-project.properties
- [SDK-180](https://incountry.atlassian.net/browse/SDK-180)
------------
Target Release
--------------
> SDK-180 [Python SDK] Add badges to README

- tests/integration/conftest.py
- tests/integration/test_methods.py
- tests/integration/test_migrate.py
- [SDK-168](https://incountry.atlassian.net/browse/SDK-168)
------------
Target Release
--------------
> SDK-168 [Python SDK] Add integration tests for OAuth

- .travis.yml
- incountry/__version__.py
- setup.py
- [SDK-160](https://incountry.atlassian.net/browse/SDK-160)
------------
Target Release
--------------
> SDK-160 [Python SDK] Release/snapshot deploying automation

- .travis.yml
- [SDK-211](https://incountry.atlassian.net/browse/SDK-211)
------------
Target Release
--------------
> SDK-211 [Python SDK] Change GIT clone configuration for Travis

- README.md
- [SDK-210](https://incountry.atlassian.net/browse/SDK-210)
------------
Target Release
--------------
> SDK-210 [Python SDK] Update README to mention Schema 2.2 changes

- .travis.yml
- README.md
- incountry/models/record.py
- incountry/validation/validate_http_response.py
- tests/integration/test_methods.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- tests/unit/test_storage.py
- tests/utils.py
- [SDK-204](https://incountry.atlassian.net/browse/SDK-204)
------------
Target Release
--------------
> [Python SDK] SDK should return create/update dates on read/find

- sonar-project.properties
- [SDK-204](https://incountry.atlassian.net/browse/SDK-204)
------------
Target Release
--------------
> SDK-204 [Python SDK] SDK should return create/update dates on read/find - 2

- tests/unit/test_http_models.py
- tests/unit/test_storage.py
- tests/utils.py
- [SDK-216](https://incountry.atlassian.net/browse/SDK-216)
------------
Target Release
--------------
> SDK-216 [Python SDK] Add unit tests for http client models

- README.md
- tests/unit/test_http_client.py
- [SDK-214](https://incountry.atlassian.net/browse/SDK-214)
------------
Target Release
--------------
> SDK-214 [Python SDK] Release v3.0.0 - minor readme fixes

- incountry/crypto_utils.py
- incountry/storage.py
- tests/integration/test_migrate.py
- tests/unit/test_storage.py
[FIX] fix migrate throwing exception with newly added date fields in batch_write
- [SDK-218](https://incountry.atlassian.net/browse/SDK-218)
------------
Target Release
--------------
> SDK-218 [Python SDK] Migration method return error

- README.md
- [SDK-214](https://incountry.atlassian.net/browse/SDK-214)
------------
Target Release
--------------
> SDK-214 [Python SDK] Release v3.0.0 - README updates

- .travis.yml
- sonar-project.properties
- travis-build.sh
Link to the JIRA ticket with requirements: https://incountry.atlassian.net/browse/DEVOPS-2115
> DEVOPS-2115: Reconfigure CI for Python SDK

- incountry/__init__.py
- incountry/crypto_utils.py
- incountry/http_client.py
- incountry/models/__init__.py
- incountry/models/find_filter.py
- incountry/models/record.py
- incountry/models/record_list_for_batch.py
- incountry/models/storage_with_env.py
- incountry/storage.py
- incountry/validation/validate_model.py
- tests/integration/conftest.py
- tests/integration/test_non_hashed.py
- tests/unit/test_crypto_utils.py
- tests/unit/test_http_client.py
- tests/unit/test_models.py
- tests/unit/test_storage.py
- tests/utils.py
- [SDK-245](https://incountry.atlassian.net/browse/SDK-245)
------------
Target Release
--------------
> SDK-245 [Python SDK] Add non hashing mode for key1-key10

- README.md
- incountry/models/find_filter.py
- incountry/storage.py
- tests/integration/test_non_hashed.py
- tests/unit/test_models.py
- [SDK-246](https://incountry.atlassian.net/browse/SDK-246)
------------
Target Release
--------------
> SDK-246 [Python SDK] Add search_keys filter support

- Pipfile
- Pipfile.lock
- README.md
- incountry/incountry_crypto.py
- incountry/models/secrets_data.py
- incountry/secret_key_accessor.py
- incountry/validation/validate_custom_encryption_config.py
- tests/unit/test_crypto.py
- tests/unit/test_models.py
- tests/unit/test_secret_key_accessor.py
- tests/unit/test_storage.py
- [SDK-248](https://incountry.atlassian.net/browse/SDK-248)
------------
Target Release
--------------
> SDK-248 [Python SDK] SDK should accept base64 encoded keys in SecretsData instead of utf-8 encoded

- README.md
- incountry/storage.py
- travis-build.sh
- [SDK-267](https://incountry.atlassian.net/browse/SDK-267)
------------
Target Release
--------------
> SDK-267 [Python SDK] File storage README

- travis-build.sh
- https://incountry.atlassian.net/browse/DEVOPS-2470
> DEVOPS-2470: Print bandit issues to travis console

- travis-build.sh
- [SDK-283](https://incountry.atlassian.net/browse/SDK-283)
------------
Target Release
--------------
> SDK-283 [Python SDK] Merge RC_3.3.0 into develop

- README.md
- [SDK-272](https://incountry.atlassian.net/browse/SDK-272)
------------
Target Release
--------------
> SDK-272 [Python SDK] Update README introduction section - config section updates

- incountry/incountry_crypto.py
- tests/integration/conftest.py
- tests/integration/test_migrate.py
- [SDK-290](https://incountry.atlassian.net/browse/SDK-290)
------------
Target Release
--------------
> SDK-290 [Python SDK] Fix inconsistency in int tests 

- setup.py
- [SDK-286](https://incountry.atlassian.net/browse/SDK-286)
------------
Target Release
--------------
> SDK-286 [Python SDK] Add py.typed file

- Pipfile
- Pipfile.lock
- [SDK-322](https://incountry.atlassian.net/browse/SDK-322)
------------
Target Release
--------------
> SDK-322 [Python SDK] Update cryptography module version

- .travis.yml
- [SDK-282](https://incountry.atlassian.net/browse/SDK-282)
------------
Target Release
--------------
> SDK-282 [Python SDK] Release SDK v3.3.0 - update travis to force use node v11

- sonar-project.properties
- [SDK-325](https://incountry.atlassian.net/browse/SDK-325)
------------
Target Release
--------------
> SDK-325 [Python SDK] Fix sonar configuration

- .travis.yml
- [SDK-282](https://incountry.atlassian.net/browse/SDK-282)
------------
Target Release
--------------
> SDK-282 [Python SDK] Release SDK v3.3.0 - update travis config to fix snyk issue

- incountry/models/__init__.py
- incountry/models/attachment_create.py
- incountry/storage.py
- tests/unit/test_storage_attachments.py
- [SDK-330](https://incountry.atlassian.net/browse/SDK-330)
------------
Target Release
--------------
> SDK-330 [Python SDK] Limit maximum attachment size

- README.md
- examples/aws-kms.py
- [SDK-254](https://incountry.atlassian.net/browse/SDK-254)
------------
Target Release
--------------
> SDK-254 [Python SDK] AWS KMS Key integration example
